---
services:
  nvim:
    build:
      context: .
      ssh:
        - default
    environment:
      - USER_ID
      - GROUP_ID
    volumes:
      - nvim-cache:/root/.cache
      - nvim-local:/root/.local
      - ./:/workspace

volumes:
  nvim-cache:
  nvim-local:
